USE [master]
GO
/****** Object:  Database [SofttOneSMSNew]    Script Date: 5/29/2025 9:54:28 AM ******/
CREATE DATABASE [SofttOneSMSNew]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SofttOneSMSNew', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SofttOneSMSNew.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SofttOneSMSNew_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SofttOneSMSNew_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SofttOneSMSNew] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SofttOneSMSNew].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SofttOneSMSNew] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET ARITHABORT OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SofttOneSMSNew] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SofttOneSMSNew] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SofttOneSMSNew] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SofttOneSMSNew] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SofttOneSMSNew] SET  MULTI_USER 
GO
ALTER DATABASE [SofttOneSMSNew] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SofttOneSMSNew] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SofttOneSMSNew] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SofttOneSMSNew] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SofttOneSMSNew] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SofttOneSMSNew] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SofttOneSMSNew] SET QUERY_STORE = OFF
GO
USE [SofttOneSMSNew]
GO
/****** Object:  User [Buddhika]    Script Date: 5/29/2025 9:54:28 AM ******/
CREATE USER [Buddhika] FOR LOGIN [Buddhika] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[tblStudent_Personal]    Script Date: 5/29/2025 9:54:28 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO